micronaut:
  application:
    name: stremio-plugin-claro

claro:
  url_config: "https://www.clarovideo.com/api/config"
  url_apa: "https://apa-api-web.clarovideo.net"
  url_mfwk_api: "https://mfwkweb-api.clarovideo.net"
