micronaut:
  application:
    name: stremio-plugin-claro
---
claro:
  url_config: "https://www.clarovideo.com"
  url_apa: "https://apa-api-web.clarovideo.net"
  url_mfwk_api: "https://mfwkweb-api.clarovideo.net"
  user: "${CLARO_USER:test}"
  password: "${CLARO_PASSWORD:test}"
  node_movies: "sapeliculas"
---
datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
---
flyway:
  datasources:
    default:
      locations: classpath:databasemigrations


